version: 2.1

orbs:
  packagecloud: packagecloud/packagecloud@0.1.0

jobs:
  test:
    working_directory: /go/src/github.com/geckoboard/statsite-rewrite-sink
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: go test -v ./...

  build:
    working_directory: /go/src/github.com/geckoboard/statsite-rewrite-sink
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: mkdir -p bin && go build -o bin/statsite-rewrite-sink
      - store_artifacts:
          path: bin
      - persist_to_workspace:
          root: .
          paths: bin/*
      # quickly verify the binary works as we expect!
      # If the output from the bin does not match the expected output it'll
      # fail the build
      - run: bin/statsite-rewrite-sink rewrite examples/envoy.in.dump | diff - examples/envoy.out.dump
  package:
    docker:
      - image: circleci/ruby:2.4.2
    steps:
      - checkout
      - run: gem install fpm --no-ri --no-rdoc --version 1.3.3
      - attach_workspace:
          at: .
      - run: |
          mkdir -p pkg tmp/bin
          cp bin/* tmp/bin
          cd pkg && fpm -C ../tmp -t deb -s dir --name statsite-rewrite-sink --version 1:1.0.0+build~${CIRCLE_BUILD_NUM}+git~${CIRCLE_SHA1} --prefix /usr/local/ --provides statsite-rewrite-sink --force .
      - persist_to_workspace:
          root: .
          paths: pkg/*
      - store_artifacts:
          path: pkg

workflows:
  version: 2
  on-push:
    jobs:
      - build
      - test
      - package:
          requires:
            - build
      - packagecloud/push:
          package-path: pkg/*.deb
          repo-fqname: geckoboard/public-packages
          os-version: ubuntu/xenial
          workspace-path: .
          filters:
            branches:
              # We don't want to allow PRs from forks to publish to our deb repo without approval
              only: master
          requires:
            - package
