version: 2
jobs:
  test:
    working_directory: /go/src/github.com/geckoboard/statsite-rewrite-sink
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: go test -v ./...

  build:
    working_directory: /go/src/github.com/geckoboard/statsite-rewrite-sink
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: mkdir -p bin && go build -o bin/statsite-rewrite-sink
      - store_artifacts:
          path: bin
      - persist_to_workspace:
          root: .
          paths: bin/*
  release:
    docker:
      - image: circleci/ruby:2.4.2
    steps:
      - checkout
      - run: |
          gem install fpm --no-ri --no-rdoc --version 1.3.3
          gem install package_cloud --no-ri --no-rdoc
      - attach_workspace:
          at: .
      - run: |
          mkdir -p pkg tmp/bin
          cp bin/* tmp/bin
          cd pkg && fpm -C ../tmp -t deb -s dir --name statsite-rewrite-sink --version 1.0.0+git~${CIRCLE_SHA1} --prefix /usr/local/ --provides statsite-rewrite-sink --force .
      - store_artifacts:
          path: pkg
      - run: package_cloud push --skip-errors geckoboard/public-geckoboard-tooling/ubuntu/xenial pkg/*.deb

workflows:
  version: 2
  on-push:
    jobs:
      - build
      - test
      - release:
          requires:
            - build
